version: '3.3'

services:
  api:
    container_name: evolution_api
    image: atendai/evolution-api
    restart: always
    ports:
      - 8080:8080
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    environment:
      - SERVER_URL=http://localhost:8080
      - DOCKER_ENV=true
      - LOG_LEVEL=ERROR
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=0417bf43b0a8969bd6685bcb49d783df
      # Configuração do MariaDB
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=mysql  # Usar "mysql" para MariaDB
      - DATABASE_CONNECTION_URI=mysql://evolution_user:senha@mariadb:3306/evolution_db
      - DATABASE_CONNECTION_DB_PREFIX_NAME=evo_
      - DATABASE_SAVE_DATA_INSTANCE=true
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha_root
      MYSQL_DATABASE: evolution_db
      MYSQL_USER: evolution_user
      MYSQL_PASSWORD: senha
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  evolution_instances:
  evolution_store:
  mariadb_data: